export interface BingoTile {
    id: string;
    text: string;
    icon: string;
}

export const bingoTiles: BingoTile[] = [
    { id: '1', text: 'Lead a conga line with at least 5 people', icon: '💃' },
    { id: '2', text: 'Win an arm wrestling match against someone', icon: '💪' },
    { id: '3', text: 'Take a selfie with 3 people you just met', icon: '📸' },
    { id: '4', text: 'Teach the macarena to someone who doesn\'t know it', icon: '🕺' },
    { id: '5', text: 'Get 3 compliments from different people', icon: '🌟' },
    { id: '6', text: 'Make someone laugh with an embarrassing story', icon: '😅' },
    { id: '7', text: 'Get 5 people to sing your favorite song', icon: '🎤' },
    { id: '8', text: 'Give a toast that makes everyone raise their glass', icon: '🥂' },
    { id: '9', text: 'Get someone to copy your best dance move', icon: '💃' },
    { id: '10', text: 'High five 10 different people in 1 minute', icon: '🖐️' },
    { id: '11', text: 'Tell a joke that makes at least 3 people laugh', icon: '😂' },
    { id: '12', text: 'Be at the top of a 3-person pyramid', icon: '🏰' },
    { id: '13', text: 'Win a limbo contest against 2 others', icon: '🎪' },
    { id: '14', text: 'Do an impression that someone can guess', icon: '🎭' },
    { id: '15', text: 'Win 3 rounds of rock, paper, scissors in a row', icon: '✌️' },
    { id: '16', text: 'Create a secret handshake with a stranger', icon: '🤝' },
    { id: '17', text: 'Challenge and win a 30-second dance battle', icon: '🕺' },
    { id: '18', text: 'Make a paper airplane that flies across the room', icon: '✈️' },
    { id: '19', text: 'Get 3 people to do the chicken dance with you', icon: '🐔' },
    { id: '20', text: 'Give a piggyback ride to someone for 30 seconds', icon: '🏃' },
    { id: '21', text: 'Start a wave that goes around the entire room', icon: '👋' },
    { id: '22', text: 'Get someone to guess your charades in 30 seconds', icon: '🎬' },
    { id: '23', text: 'Make a funny face that someone tries to copy', icon: '🤪' },
    { id: '24', text: 'Successfully perform a magic trick for someone', icon: '🎩' },
    { id: '25', text: 'Win a 30-second pillow fight against someone', icon: '🛏️' },
    { id: '26', text: 'Create a human chain with 6 or more people', icon: '⛓️' },
    { id: '27', text: 'Be the last one standing in musical chairs', icon: '🪑' },
    { id: '28', text: 'Teach your robot dance to 2 other people', icon: '🤖' },
    { id: '29', text: 'Win 2 thumb wrestling matches in a row', icon: '👍' },
    { id: '30', text: 'Get 3 people to guess your animal impression', icon: '🐮' },
    { id: '31', text: 'Make someone fail saying your tongue twister', icon: '👅' },
    { id: '32', text: 'Be the last player in a game of Simon Says', icon: '👑' },
    { id: '33', text: 'Do the moonwalk for at least 10 seconds', icon: '🌙' },
    { id: '34', text: 'Get 5 strangers to join your conga line', icon: '🚂' },
    { id: '35', text: 'Successfully untangle a 6-person human knot', icon: '🔄' },
    { id: '36', text: 'Perform an air guitar solo that gets applause', icon: '🎸' },
    { id: '37', text: 'Do the floss dance until someone joins you', icon: '🦷' },
    { id: '38', text: 'Create a group pose with 4 random people', icon: '🎭' },
    { id: '39', text: 'Start a whisper chain that reaches 10 people', icon: '👂' },
    { id: '40', text: 'Do jumping jacks until someone joins you', icon: '⭐' },
    { id: '41', text: 'Keep a hot potato game going for 2 minutes', icon: '🥔' },
    { id: '42', text: 'Get 3 people to jam to your beatbox', icon: '🎵' },
    { id: '43', text: 'Win a staring contest against someone', icon: '👀' },
    { id: '44', text: 'Hold a statue pose until 3 people notice', icon: '🗽' },
    { id: '45', text: 'Start an air band with 3 other people', icon: '🥁' },
    { id: '46', text: 'Get someone to twist dance with you for 30s', icon: '💫' },
    { id: '47', text: 'Start a clapping game that lasts 1 minute', icon: '👏' },
    { id: '48', text: 'Make a shadow puppet that someone can guess', icon: '🐰' },
    { id: '49', text: 'Lead a chant that at least 5 people join', icon: '📣' },
    { id: '50', text: 'Get 3 people to do the hokey pokey with you', icon: '💫' }
]; 