export interface BingoTile {
    id: string;
    text: string;
    icon: string;
}

export const bingoTiles: BingoTile[] = [
    { id: '1', text: 'Start a conga line', icon: '💃' },
    { id: '2', text: 'Challenge someone to arm wrestling', icon: '💪' },
    { id: '3', text: 'Take a group selfie', icon: '📸' },
    { id: '4', text: 'Do the macarena', icon: '🕺' },
    { id: '5', text: 'Give someone a compliment', icon: '🌟' },
    { id: '6', text: 'Share an embarrassing story', icon: '😅' },
    { id: '7', text: 'Start a sing-along', icon: '🎤' },
    { id: '8', text: 'Make a toast', icon: '🥂' },
    { id: '9', text: 'Do your best dance move', icon: '💃' },
    { id: '10', text: 'High five three people', icon: '🖐️' },
    { id: '11', text: 'Tell a joke', icon: '😂' },
    { id: '12', text: 'Create a human pyramid', icon: '🏰' },
    { id: '13', text: 'Start a limbo contest', icon: '🎪' },
    { id: '14', text: 'Do an impression', icon: '🎭' },
    { id: '15', text: 'Play rock, paper, scissors', icon: '✌️' },
    { id: '16', text: 'Create a secret handshake', icon: '🤝' },
    { id: '17', text: 'Start a dance battle', icon: '🕺' },
    { id: '18', text: 'Make a paper airplane', icon: '✈️' },
    { id: '19', text: 'Do the chicken dance', icon: '🐔' },
    { id: '20', text: 'Give someone a piggyback ride', icon: '🏃' },
    { id: '21', text: 'Start a wave', icon: '👋' },
    { id: '22', text: 'Play charades', icon: '🎬' },
    { id: '23', text: 'Make a funny face', icon: '🤪' },
    { id: '24', text: 'Do a magic trick', icon: '🎩' },
    { id: '25', text: 'Start a pillow fight', icon: '🛏️' },
    { id: '26', text: 'Create a human chain', icon: '⛓️' },
    { id: '27', text: 'Play musical chairs', icon: '🪑' },
    { id: '28', text: 'Do the robot dance', icon: '🤖' },
    { id: '29', text: 'Start a thumb war', icon: '👍' },
    { id: '30', text: 'Make animal noises', icon: '🐮' },
    { id: '31', text: 'Create a tongue twister', icon: '👅' },
    { id: '32', text: 'Play simon says', icon: '👑' },
    { id: '33', text: 'Do the moonwalk', icon: '🌙' },
    { id: '34', text: 'Start a conga line', icon: '🚂' },
    { id: '35', text: 'Make a human knot', icon: '🔄' },
    { id: '36', text: 'Play air guitar', icon: '🎸' },
    { id: '37', text: 'Do the floss dance', icon: '🦷' },
    { id: '38', text: 'Create a group pose', icon: '🎭' },
    { id: '39', text: 'Start a whisper chain', icon: '👂' },
    { id: '40', text: 'Do jumping jacks', icon: '⭐' },
    { id: '41', text: 'Play hot potato', icon: '🥔' },
    { id: '42', text: 'Make a beatbox beat', icon: '🎵' },
    { id: '43', text: 'Start a staring contest', icon: '👀' },
    { id: '44', text: 'Create a human statue', icon: '🗽' },
    { id: '45', text: 'Play air drums', icon: '🥁' },
    { id: '46', text: 'Do the twist dance', icon: '💫' },
    { id: '47', text: 'Start a clapping game', icon: '👏' },
    { id: '48', text: 'Make shadow puppets', icon: '🐰' },
    { id: '49', text: 'Create a group chant', icon: '📣' },
    { id: '50', text: 'Do the hokey pokey', icon: '💫' }
]; 